version: '2'

services:

  django_project:
    build:
      dockerfile: Dockerfile
      context: .
    image: django_docker:latest
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
    env_file:
      - .env

    command: >
      bash -c "./manage.py collectstatic --noinput && ./manage.py makemigrations && ./manage.py migrate && gunicorn -b 0.0.0.0:8000 mysite.wsgi:application"
    

    restart: always

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    image: nginx_for_django
    volumes:
      - static_volume:/django/static
      - media_volume:/django/media
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
      - "${NGINX_EXTERNAL_SSL_PORT}:443"

    restart: always

volumes:
  static_volume:
  media_volume:
  certs:
  vhost:
  html:
  acme: